### PR TITLE
adding mqtt for stand-alone mode

### PR DESCRIPTION
**Pull request by eporsche**
This pull request will add the ability to run this addon standalone for Home Assistant Container installations.

### CODE REVIEW

**Comment by eporsche** [comment]
I am not sure about the "addon: 8cd50eef_ha-sip-next" changes in the readme which came from the other pull request.

**Comment by arnonym** [comment]
This is done automatically by the build.sh build-next script. we need to redo those!

**Review by arnonym — APPROVED** [review]

**Comment by arnonym** [comment]
Can you rebase a last time?

**Comment by eporsche** [comment]
Not sure what todo next. What do you mean by rebase?

**Comment by arnonym** [comment]
Rebase to the next branch, or merge next into your branch. There are some conflicts which don't allow to merge this branch into my.

**Comment by eporsche** [comment]
hopefully I did everything right..

**Comment by arnonym** [comment]
That does not look too well. If you add me to your fork of the repo, I could try to correct that?

**Comment by arnonym** [comment]
I merged your contributions to the next branch! If you want, you can re-check if everything is correct. I'll create a release in the next few days! Thanks again for your work!

**Comment by arnonym** [comment]
I still have a question: is it possible to write the payload to `mqtt.publish` as yaml also? For the stdin method the yaml is automatically converted to json when sending it. Would be easier to read.

**Comment by arnonym** [comment]
And would you like to be mentioned in the release notes?

**Comment by eporsche** [comment]
> I merged your contributions to the next branch! If you want, you can re-check if everything is correct. I'll create a release in the next few days! Thanks again for your work!

The next branch works great! I tried the run-local and standalone version.

Thank you very much for creating this sip addon and making the standalone addition possible!

Sorry for my bad git skills though. I guess I need to improve those!

> And would you like to be mentioned in the release notes?

Sure. :)

**Comment by arnonym** [comment]
Thanks for testing!

The git situation was not that easy to solve, because i rewrote history to have a nice commit history. My bad!

And I got you covered: https://github.com/arnonym/ha-plugins/blob/next/ha-sip/CHANGELOG.md#37

If you want you can make a post to https://community.home-assistant.io/t/home-assistant-sip-gateway/333694 after the release, because they were a few people asking for running ha-sip outside of home-assistant OS.

**Comment by arnonym** [comment]
I've just released 3.7! :partying_face:

**Comment by eporsche** [comment]
Left a quick note in the thread you mentioned! 😉

**Comment by eporsche** [comment]
😆 - I used the search function! 😉 But then I also read through the post.. just to find some other use cases!

**Pull request closed without merging**
